### ISSUE TITLE
API Init always returns FAILED

### ISSUE THREAD

**Issue by SokuiSenpai** [ChromaControl/RzChromaBroadcastAPI.NET#3]
Using the BroadcastAPI Init always returns failed for every version > 1.0.0 of this project.
Is there a special Guid I have to pass or am I missing something?

**Comment by AndrewBabbitt97** [comment]
You must reach out to Razer to get a GUIDs. They are specific to Razer and only they can generate new ones. After getting one you will have to wait for a new version of Synapse to be released to use it.
